# Generated by Django 4.1.7 on 2023-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_students_email_students_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/placeholder.png",
                null=True,
                upload_to="Posted_Images",
            ),
        ),
    ]
